/** Re-export shared check expression engine (`@oko/engine`). */
export {
  CheckParseError,
  cellGetterToContext,
  combineCheckExpression,
  evaluateCheckExpression,
  evaluateCondition,
  evaluateEquality,
  evaluateExpr,
  expressionUsesForm,
  extractCellKRefs,
  extractCellRefs,
  formatCheckErrorMessage,
  normalizeCheckExpression,
  parseArithmetic,
  parseCellCall,
  type CellGetter,
  type CellKRef,
  type CellRef,
  type CheckEvalResult,
  type EvalContext,
  type Expr,
} from "@oko/engine";
